# Generated by Django 5.2.7 on 2026-01-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_reservation_account_order_orderdetail'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderdetail',
            table='actions_order_details',
        ),
    ]
