# Generated by Django 5.2.7 on 2026-01-08 13:58

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
