# Generated by Django 5.2.7 on 2025-12-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_date_joined_alter_account_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='users_accounts',
        ),
        migrations.AlterModelTable(
            name='customer',
            table='users_customers',
        ),
        migrations.AlterModelTable(
            name='email',
            table='users_emails',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='users_employees',
        ),
    ]
